name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'zulu'
        cache: maven
    
    - name: Build
      run: mvn -B clean install -DskipTests

  test:
    name: 🧪 Test
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'zulu'
        cache: maven
    
    - name: Run tests
      run: mvn -B test
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/target/surefire-reports/'

  package:
    name: 📦 Package
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'zulu'
        cache: maven
    
    - name: Package
      run: mvn -B package -DskipTests
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application-jars
        path: '**/target/*.jar'
